name: Inputs and Outputs
on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: "Skip deployment and only print build output"
        default: false
      target:
        type: environment
        description: "Which environment the workflow will target"
      tag:
        type: choice
        options: [v1, v2, v3]
        default: v3
        description: "Release from which to build and deploy"
      build-status:
        type: choice
        options: [success, failure]
        default: success
        description: "Choose the build status for the demo"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo "${{env.GITHUB_OUTPUT}}"


